language: php

sudo: false

git:
  depth: 1

branches:
  only: 
    - 1.x
    - 2.x

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer --dev install

script: phpunit
