language: php

sudo: false

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty

git:
  depth: 1

branches:
  only: 
    - 1.x
    - 2.x

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer --dev install

script: vendor/bin/phpunit
