name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHP 7.3
        uses: php-actions/phpunit@v3
        with:
          php_version: 7.3

      - name: PHP 7.4
        uses: php-actions/phpunit@v3
        with:
          php_version: 7.4
