name: CI

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v5

            -   name: PHP 5.6
                uses: php-actions/phpunit@v3
                with:
                    php_version: 5.6

            -   name: PHP 7.0
                uses: php-actions/phpunit@v3
                with:
                    php_version: 7.0

            -   name: PHP 7.1
                uses: php-actions/phpunit@v3
                with:
                    php_version: 7.1

            -   name: PHP 7.2
                uses: php-actions/phpunit@v3
                with:
                    php_version: 7.2

            -   name: PHP 7.3
                uses: php-actions/phpunit@v3
                with:
                    php_version: 7.3

            -   name: PHP 7.4
                uses: php-actions/phpunit@v3
                with:
                    php_version: 7.4
